### ISSUE TITLE
Ownership isn't set properly on /etc/authorized_keys

### ISSUE THREAD

**Issue by seanw2020** [panubo/docker-sshd#32]
I didn't see anybody else report this problem, so maybe I'm doing something wrong, but `docker logs` shows `Authentication refused: bad ownership or modes for file /etc/authorized_keys/foo`. This fixes it, after creating the container:

```bash
docker exec -t bar bash -c 'chown foo:foo /etc/authorized_keys/foo'
```

Steps to reproduce:
```bash
scp ~/.ssh/foo.pub bar:
docker run --name baz -d -p 2222:22 --network-alias=howdy --network=baz.local \
  --mount type=bind,source=$(pwd)/foo.pub,target=/etc/authorized_keys/foo \
  -e SSH_USERS="foo:1001:1001" docker.io/panubo/sshd:1.0.3
```

**Comment by Frederik-Baetens** [comment]
I think this is because your uid differs from the one set in the docker container, but i don't know why that should matter.

**Comment by Frederik-Baetens** [comment]
It is because uid and gid are preserved trough docker volume mounts, so if the host uid differs from the docker user uid, the docker user has no permissions to open the ssh key file.

**Comment by masenocturnal** [comment]
In the entry script it does a chmod 0755 on /etc/authorized_keys/${USER} .

I believe this just needs to be changed to 0600 like it is for the root user.

**Comment by Frederik-Baetens** [comment]
It would also need to do a chown and chgrp then I think

**Comment by gaeljw** [comment]
I'm having the same issue.
I am using the testcontainers library to start a "fake" sftp server.

I ended up doing following:
- don't bind volumes for the key,
- after container startup, copy key to `/etc/authorized_keys/$user` (`docker cp` / `copyFileToContainer`)
- after container startup, run `chmod $user:$user /etc/authorized_keys/$user` (`docker exec` / `execInContainer`)

**Comment by macropin** [comment]
The issue here is that the uid/gid of the authorized key outside the container doesn't match the  uid/gid within the container (as defined with `SSH_USERS`). In other words the authorized key files need to have the same uid and gid of the corresponding user, or alternatively be owned by root.

I think the best resolution here is that we add an init check that warns when the keys are not owned by root or the correct user. Automatically changing uid/gid would likely do more harm than good.

(As an aside: It is also worth noting that the uid/gid are not preserved through mounts when using Docker on MacOS, so these are always root owned and always work on MacOS)
