### ISSUE TITLE
Tunneling has stopped working

### ISSUE THREAD

**Issue by krotton** [panubo/docker-sshd#36]
A version deployed today to Docker Hub changes behavior with regard to tunneling. Connecting to the remote with a tunnel open works as it has before:

```sh
--- ~ » ssh -N -L 12345:remote:2345 root@sshd

```

... but actually trying to communicate with the remote service using the local port fails with:

```sh
channel 2: open failed: administratively prohibited: open failed
```

Something must have changed in the default config that prohibits connecting out to a remote service from the container.

**Comment by AshleyRoll** [comment]
I also was bitten by this.

I already have had to override the command line for my container, and so I added `-o AllowTcpForwarding=yes` to it to make it work again.

For instance when running in an Azure container, I use the following override:
```
az container create [...etc ..] 
--command-line "/entry.sh /usr/sbin/sshd -D -e -f /etc/ssh/sshd_config -p 22 -o StrictModes=no -o ClientAliveInterval=4 -o AllowTcpForwarding=yes"
```

Note that I don't get the option in Azure containers to override just the command line args, I have to override the full entry point.

Would it be possible to modify the entry.sh to provide a variable to add additional overrides rather than having to replace the entire command line?

Hope that helps.
Ash.

**Comment by Frederik-Baetens** [comment]
Yup, had to revert back to 1.0.3 to fix this, setting GATEWAY_PORTS to true did not resolve this.

**Comment by macropin** [comment]
Support for enabling TCP Forwarding has been added in 8c073c70a13379324bddffadd94122c3ab6a49a1
